In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [64]:
data=pd.read_csv("Social_Network_Ads.csv")
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [65]:
X=data.iloc[:,2:4].values
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [66]:
y=data.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [68]:
print(X_train.shape)
print(X_test.shape)

(320, 2)
(80, 2)


In [69]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_train

array([[-1.49390125, -1.5287008 ],
       [-0.07788111,  0.70692282],
       [ 0.29972426, -0.18732663],
       [ 0.01652023,  1.2732808 ],
       [-0.92749319, -0.96234282],
       [-1.02189453, -1.55850912],
       [-1.21069722,  0.28960641],
       [-1.30509856, -0.42579315],
       [-1.21069722,  0.52807293],
       [-0.07788111,  0.14056484],
       [ 2.09334977, -0.81330124],
       [-1.68270393,  0.37903136],
       [ 0.29972426,  0.05113989],
       [ 0.01652023, -0.42579315],
       [ 1.33813903,  2.04829699],
       [-0.07788111,  0.05113989],
       [-0.73869051, -1.61812575],
       [ 0.11092158,  0.05113989],
       [-0.26668379, -0.3363682 ],
       [-0.26668379,  0.17037315],
       [-0.45548648, -0.78349293],
       [-0.07788111,  0.22998978],
       [-1.77710528, -1.29023428],
       [-0.07788111,  2.22714688],
       [ 0.96053366, -1.02195945],
       [-0.54988782,  2.40599677],
       [-0.36108514, -1.3200426 ],
       [ 1.054935  ,  0.58768956],
       [-0.07788111,

In [70]:
X_test=scaler.transform(X_test)
X_test

array([[-1.77710528, -1.49889249],
       [-0.17228245,  0.17037315],
       [ 0.96053366, -1.17100102],
       [-0.26668379,  0.28960641],
       [ 0.86613232, -0.57483472],
       [-0.26668379, -0.42579315],
       [-0.26668379, -1.37965923],
       [-1.87150662, -0.75368461],
       [-0.73869051, -0.21713494],
       [ 1.81014575, -0.27675157],
       [ 0.20532292, -0.66425967],
       [ 2.09334977,  0.40883967],
       [ 0.20532292,  0.05113989],
       [-0.17228245,  0.88577271],
       [-0.83309185,  0.31941473],
       [-0.54988782,  1.51174732],
       [ 0.20532292,  0.17037315],
       [ 0.01652023, -0.54502641],
       [ 1.52694172, -1.29023428],
       [-0.26668379, -0.30655989],
       [-1.02189453, -0.36617652],
       [ 0.86613232,  2.22714688],
       [-1.02189453,  0.58768956],
       [-1.58830259,  0.08094821],
       [-0.54988782, -1.5287008 ],
       [ 0.11092158,  1.92906373],
       [ 1.7157444 ,  1.89925542],
       [ 0.39412561,  0.17037315],
       [-1.11629588,

In [75]:
k=int(np.floor(np.sqrt(X_train.shape[0])))
k

17

In [98]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=k)

In [99]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=17)

In [100]:
y_pred=knn.predict(X_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0], dtype=int64)

In [101]:
y_pred.shape

(80,)

In [102]:
y_test.shape

(80,)

In [103]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.925

In [104]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[45,  5],
       [ 1, 29]], dtype=int64)